<?php
function storleden_module_theme($existing, $type, $theme, $path) {
  return array(
	  	'text_slider' => array(
	            			'variables' => array(	                		
	                						  'nodesArray' => 'slides'
	            							),
	        			),
	    'latest_projects' => array(
	    						'variables' => array(
	    										  'nodes' => 'nodes'
	    										)
	    					),
	    'tjanster' => array(
	    						'variables' => array(
	    										  'nodes' => 'nodes'
	    										)
	    					),
	    'products_angular' => array(
	    						'variables' => array(
	    										  'nodes' => 'nodes'
	    										)
	    					),
	    'screen_image_text' => array(
	    						'variables' => array(
	    										  'node' => 'node'
	    										)
	    					),
						    						    					
	    'test' => array(
	    						'variables' => array(
	    										  'node' => 'node'
	    										)
	    					),
	    'our_products_slider' => array(
	    						'variables' => array(
	    										  'nodes' => 'nodes'
	    										)
	    					),	    						
    	);
}